version: 2.1

orbs:
  haskell: haskell-works/haskell-build@4.1.7
  github: haskell-works/github-release@1.2.1
  hackage: haskell-works/hackage@1.4.1

workflows:
  multiple-ghc-build:
    jobs:
      - haskell/build:
          name: GHC 8.2.2
          executor: haskell/ghc-8_2_2

      - haskell/build:
          name: GHC 8.4.4
          executor: haskell/ghc-8_4_4

      - haskell/build:
          name: GHC 8.6.4
          executor: haskell/ghc-8_6_4

      - haskell/build:
          name: GHC 8.8.3
          executor: haskell/ghc-8_8_3

      - github/release-cabal:
          name: GitHub Release
          context: haskell-ci
          requires:
            - GHC 8.2.2
            - GHC 8.4.4
            - GHC 8.6.4
            - GHC 8.8.3
          checkout: true
          filters:
            branches:
              only: master

      - hackage/upload:
          context: haskell-ci
          publish: true
          requires:
            - GitHub Release
          username: ${HACKAGE_USER}
          password: ${HACKAGE_PASS}
